@include('requests.create-edit',
['description' => old('description'),
'due_date' => old('due_date'),
'quantity' => old('quantity'),
'paper_type' => old('paper_type'),
'colored' => old('colored'),
'stapled' => old('stapled'),
'paper_size' => old('paper_size'),
'front_back' => old('front_back'),
])